init:
  - echo init
install:
  - echo install
  - python --version || echo failed
  - python -c "import struct; print(struct.calcsize('P') * 8)" || echo failed
  - python -c "import platform; print(platform.architecture()[0])" || echo failed


build: off  # do not run MSBuild, build stuff at install step

test_script:
  - echo test_script

after_test:
  - echo after_test
