environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "64"
init:
  # Override default Python version/architecture
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -c "import platform; print('Python', platform.python_version(), platform.architecture()[0])"
  - pip --version || echo failed
  - curl --version || echo failed
  - bash --version || echo failed

install:
  - pip install cffi || echo failed
  - pip install coveralls || echo failed
  - pip install -r requirements.txt
  - winrs -r:localhost cmd.exe /c "echo hello"

build: off  # Do not run MSBuild, build stuff at install step

build_script:
  - echo build_script

test_script:
  - py.test -v --cov-report=term-missing --cov=.

after_test:
  - echo after_test
